### ISSUE TITLE
Dimmed videos temporarily un-dim during "inline playback"

### ISSUE THREAD

**Issue by netjeff** [EvHaus/youtube-hide-watched#161]
YT recently added an "inline playback" feature:  When you hover, the thumbnail is replaced with the actual video playback.  YT has a new setting to control inline playback, in "Settings", "Playback and Performance", "Browsing".  Turning off inline playback restores the "auto-preview" feature, that shows a few seconds of playback on hover.

During the new inline playback, the video is un-dimmed.  When you move the pointer away, the inline playback stops, and the video returns to dimmed.  During the "auto preview" the video remains dimmed.

It would be nice if the videos remained dimmed even during inline playback (just like auto-preview).  Often I unintentionally hover over watched/dimmed videos.  I don't mind that YT starts playback, but the un-dimming catches my eye.  So would be nice if the video remained dimmed during inline playback.

For me, I've turned off the new inline playback.  But other's might like to keep it on, and yet still have dimmed videos remain dimmed during inline playback.

**Comment by netjeff** [comment]
I tried changing the 'dimmed' styles ...

```css
.YT-HWV-WATCHED-HIDDEN { display: none !important }
.YT-HWV-WATCHED-DIMMED { opacity: 0.3 }
.YT-HWV-SHORTS-HIDDEN  { display: none !important }
.YT-HWV-SHORTS-DIMMED  { opacity: 0.3 }
```

... to add a `!important` like the 'hidden' styles.  But videos still un-dim during inline playback.

Keeping the videos dimmed during inline playback is probably going to take more work.
