### ISSUE TITLE
Video grid becomes misaligned when toggling watched videos

### ISSUE THREAD

**Issue by hugo9655** [EvHaus/youtube-hide-watched#272]
Hiding all watched videos causes the grid to become misaligned with uneven spacing. Im pretty sure its because the CSS is different for the first grid items which have the `is-in-first-column=""` attribute.

Is there a way around this?

**Comment by EvHaus** [comment]
I'm not seeing the issue you're describing. Could you include a screenshot?

**Comment by netjeff** [comment]
@hugo9655, are you still experiencing these symptoms?

**Comment by Chuchzilla** [comment]
Yeah this happens to me also.

I does seem to be caused by some padding added to the left of the first item in each row. If an item is suppose to be the first item of it's 'true' row it has some padding to the left of it no matter what column it end up in.

![Image](https://github.com/user-attachments/assets/b5294532-c360-47bf-9ae8-2327c13ca903)

**Comment by hugo9655** [comment]
Ive fixed this myself using Stylus and CSS.

Its not an issue on the home/subscription page anymore, only on channel video pages.

If you want, import this:

```css
@-moz-document regexp("https:\\/\\/www\\.youtube\\.com\\/[^/]+?\\/videos") {
	/* Fix misaligned video grid on channel page */
	ytd-rich-grid-renderer #contents {
	    gap: 16px;
	    
	    > ytd-rich-item-renderer {
	        margin: 0 0 16px 0;
	    }
	}
}
```
